apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cronjob
  name: cronjob
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cronjob
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cronjob
    spec:
      containers:
      - env:
        - name: host
          value: foohost
        image: docker.io/bdecoste/cronjob:1.0
        imagePullPolicy: Always
        name: cronjob
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
        - /bin/sh
        - -c
        - |
          until curl -fsI http://localhost:15021/healthz/ready; do echo \"Waiting for Sidecar...\"; sleep 3; done;
          echo \"Sidecar available. Running the command...\";
          /testscript.sh $host;
          x=$(echo $?); curl -fsI -X POST http://localhost:15020/quitquitquit && exit $x
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
